# Generated by Django 4.2.5 on 2023-09-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='about_scripture_quote',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_scripture_reference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
