# Generated by Django 4.2.5 on 2023-09-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='read_time',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='howpage',
            name='read_time',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='weeklywordpage',
            name='read_time',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
