# Generated by Django 4.2.5 on 2023-09-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogindexpage_formfield_howindexpage_howpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopage',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='videopage',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
