# Generated by Django 4.2.5 on 2023-09-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_videopage_date_created_videopage_date_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesocial',
            old_name='facebook_url',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='sitesocial',
            old_name='instagram_url',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='sitesocial',
            old_name='linkedin_url',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='sitesocial',
            old_name='threads_url',
            new_name='threads',
        ),
        migrations.RenameField(
            model_name='sitesocial',
            old_name='twitter_url',
            new_name='tiktok',
        ),
        migrations.RenameField(
            model_name='sitesocial',
            old_name='youtube_url',
            new_name='twitter',
        ),
        migrations.AddField(
            model_name='sitesocial',
            name='youtube',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
