# Generated by Django 4.2.5 on 2023-09-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_facebook_url_sitesocial_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesocial',
            name='slug',
        ),
    ]
