# Generated by Django 4.2.5 on 2023-09-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpage_options_alter_howpage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='allow comments'),
        ),
        migrations.AddField(
            model_name='howpage',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='allow comments'),
        ),
        migrations.AddField(
            model_name='weeklywordpage',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='allow comments'),
        ),
    ]
