# Generated by Django 4.2.5 on 2023-09-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpage_allow_comments_howpage_allow_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='post_author',
        ),
        migrations.RemoveField(
            model_name='howpage',
            name='how_author',
        ),
        migrations.RemoveField(
            model_name='weeklywordpage',
            name='word_author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
