# Generated by Django 4.2.5 on 2023-10-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogindexpage_banner_howindexpage_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='blogpage',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blog_likes', to='blog.ipmodel'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='blog_views', to='blog.ipmodel'),
        ),
        migrations.AddField(
            model_name='howpage',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='how_likes', to='blog.ipmodel'),
        ),
        migrations.AddField(
            model_name='howpage',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='how_views', to='blog.ipmodel'),
        ),
        migrations.AddField(
            model_name='weeklywordpage',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='word_likes', to='blog.ipmodel'),
        ),
        migrations.AddField(
            model_name='weeklywordpage',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='word_views', to='blog.ipmodel'),
        ),
    ]
