# Generated by Django 4.2.5 on 2023-12-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_rename_video_index_page_importantpages_resources_index_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='about_us_article',
            field=models.BooleanField(default=False),
        ),
    ]
